#-------------------------------
# General Site Settings

menu:
# - {name: 'Projects', url: ''}
- {name: 'Notes.',     url: 'notes'}
- {name: 'Me.',    url: 'me'}

#-------------------------------
# Projects Section

projects:
- {name: 'Book of Ashes', description: 'Tactical RPG / Roguelike',  url: 'BookOfAshes'}
- {name: 'Discordant',  description: 'Rhythm-based Bullet Hell', url: 'Discordant'}
# - {name: 'Arcana',   url: 'Arcana'}
# - {name: 'Playing with Systems', description: 'Graduate Thesis', url: 'Systems'}
- {name: 'Crisis',  description: 'Educational Negotiation Boardgame', url: 'Crisis'}
- {name: 'Waste Land',  description: 'Educational Energy Politics Boardgame', url: 'Wasteland'}
- {name: 'Split', description: 'Cooperative Puzzle Platformer Jam Game', url: 'Split'}

#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/eetuleppala'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/eetuleppala'}
- {icon: 'envelope',  link: 'mailto:eetuleppala@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Eetu Leppälä game desiner balancing design portfolio UI/UX tactical RPG boardgames hire experienced'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
